### ISSUE TITLE
[Ventoy] None of the applications are included in the PE after building

### ISSUE THREAD

**Issue by TheNicestGuy24** [PhoenixPE/PhoenixPE#86]
﻿

Checklist
---------
- [x] I looked at https://github.com/PhoenixPE/PhoenixPE/wiki/FAQ to see if my question has already been answered.
- [x] I performed a search in the issue tracker for similar issues using keywords relevant to my problem, such as the error message I got from the log.

Report
---------
﻿

**Describe what is happening**
A clear and concise description of the issue you are experiencing. 

I have tried both the 2024-02-09 and the 2024-01-14 releases and even selecting just 1 application it downloads the application and builds the application and appears that everything works, however, when you then look in the workbench\phoenixpe\target\programfiles or porgramfiles (x86), none of the applications that it downloaded and built are there.  So of couse when you launch the ISO and boot into the PE, there is a link in the start menu to these applications, but none of then work because they don't have the associated files in the PE to launch them.  

Also, things like Mozilla Firefox fail to write registry entries when building due to an unauthorized operation

I was trying to find an active forum where I could get some help on figuring this out, but I haven't found one, is there a community forum that exists where users can discuss issues to try and fix issues such as this?

**To Reproduce**
Step-by-step instructions on how to reproduce the behavior:
1. Go to 'Download a clean copy of PhoenixPE'
2. Add your source in configure source
3. Unclick "Mozilla Firefox" in the build under Network as it always errors due to failing to write to the registry.
4. Click on 'Aomei Backupper in applications \ backup & imaging to include that program'
5. Click "Build"
6. It appears to build fine, yet if you go into the workbench\phoenixpe\targe\program files folders, neither of them have the application files

**Expected behavior**
I expect that the application would be listed under program files folder after building as well as launch in the PE once booted into it.

**Screenshots/Logs**

![image](https://github.com/PhoenixPE/PhoenixPE/assets/164514930/4092ebcd-32e8-4371-a33e-c3018f985d92)
![image](https://github.com/PhoenixPE/PhoenixPE/assets/164514930/a653c556-c9df-40cb-8e5f-252d4279d41f)
[BuildLog_2024_03_22_074524_Project_PhoenixPE.txt](https://github.com/PhoenixPE/PhoenixPE/files/14723402/BuildLog_2024_03_22_074524_Project_PhoenixPE.txt)

**Comment by TheNicestGuy24** [comment]
The build log that I attached is one that includes a default build with only Aomei Backupper checked aside from the default options and shows Mozilla fails to write to registry.

However, you can uncheck Mozilla, leave Aomei Backupper checked and it downloads Aomei Backupper from the web and builds fine with no issue in the logs, yet the application isn't actually there in the PE.

**Comment by homes32** [comment]
Hello,

> I have tried both the 2024-02-09 and the 2024-01-14 releases and even selecting just 1 application it downloads the application and builds the application and appears that everything works, however, when you then look in the workbench\phoenixpe\target\programfiles or porgramfiles (x86), none of the applications that it downloaded and built are there. So of couse when you launch the ISO and boot into the PE, there is a link in the start menu to these applications, but none of then work because they don't have the associated files in the PE to launch them.
 
This sees very very strange. 

You will never see anything in `Program Files (x86)` so that is normal. If Run From RAM is set programs will be in `%TargetDir%\Program Files`. If Run from RAM is not set they will be in `%OutputDir%\Programs` (in your case `C:\PhoenixPE-2024-01-14-x64\Output\PhoenixPE\Programs`)

Looking at your logs I can see that the files are being extracted to the target dir.
```
 [Success] FileVersion - File [C:\PhoenixPE-2024-01-14-x64\Workbench\PhoenixPE\Target\Program Files\Firefox\firefox.exe]'s version is [124.0.0.8836] (FileVersion,"%TargetPrograms%\%ProgramFolder%\%ProgramExe%",%ProgramExeVer%)
  [Success] FileVersion - Local variable [%ProgramExeVer%] set to [124.0.0.8836] (FileVersion,"%TargetPrograms%\%ProgramFolder%\%ProgramExe%",%ProgramExeVer%)
```

and

```
[Success] FileVersion - File [C:\PhoenixPE-2024-01-14-x64\Output\PhoenixPE\Programs\AOMEI Backupper\Backupper.exe]'s version is [7.3.4.0] (FileVersion,"%TargetPrograms%\%ProgramFolder%\%ProgramExe%",%ProgramExeVer%)
  [Success] FileVersion - Local variable [%ProgramExeVer%] set to [7.3.4.0] (FileVersion,"%TargetPrograms%\%ProgramFolder%\%ProgramExe%",%ProgramExeVer%)
```
and
```
[Success] IniWrite - Key [versionCode] and it's value [2] written to [C:\PhoenixPE-2024-01-14-x64\Output\PhoenixPE\Programs\AOMEI Backupper\Version.ini] (IniWrite,"%TargetPrograms%\%ProgramFolder%\Version.ini","VersionInfo","versionCode",2)
```

we can also see that we are able to use the Windows API to extract the version information from the files in the target, and write to some config files, so we know that the files were extracted to where they are suppose to be. That's really all I can tell from the logs. I have no idea what your computer did to them after the build was completed.

> Also, things like Mozilla Firefox fail to write registry entries when building due to an unauthorized operation

Windows/Defender recently aggressively started blocking registry operations to the keys that control default browser in newer version of windows.

as a temporary workaround  you can uncheck "set as default browser" or comment out lines 362-363 like this
```
//RegWrite,HKLM,0x1,"Tmp_Software\Microsoft\Windows\Shell\Associations\UrlAssociations\http\UserChoice","ProgId","FirefoxURL"
//RegWrite,HKLM,0x1,"Tmp_Software\Microsoft\Windows\Shell\Associations\UrlAssociations\https\UserChoice","ProgId","FirefoxURL"
```
 
> I was trying to find an active forum where I could get some help on figuring this out, but I haven't found one, is there a community forum that exists where users can discuss issues to try and fix issues such as this?

yes. PhoenixPE as an active thread in [The Oven forum](https://theoven.org/viewforum.php?f=17) and is listed on the main github readme and on the PhoenixPE UI main script.

**Comment by homes32** [comment]
> Also, things like Mozilla Firefox fail to write registry entries when building due to an unauthorized operation
 
Fixed in [f2d1073](https://github.com/PhoenixPE/PhoenixPE/commit/f2d1073e38d52025b63bb33c32e54c2f0c013786)

**Comment by PCAssistSoftware** [comment]
> As for a forum where things like this can be discussed, I would love to use theoven (and I posted there many times years ago), however, if you go to their forums now and look, they have taken away the login feature.

Login button appearing fine for me, just ensure you scroll down to the bottom and lick Accept cookies first - then login and register boxes will reappear at the top right of the page

![image](https://github.com/PhoenixPE/PhoenixPE/assets/10872799/8d547bf0-f8ed-476a-89b4-d4a7c99c1357)

![image](https://github.com/PhoenixPE/PhoenixPE/assets/10872799/5657cf51-6e41-46e3-a74c-93901bd32031)

**Comment by homes32** [comment]
> > As for a forum where things like this can be discussed, I would love to use theoven (and I posted there many times years ago), however, if you go to their forums now and look, they have taken away the login feature.
> 
> Login button appearing fine for me, just ensure you scroll down to the bottom and lick Accept cookies first - then login and register boxes will reappear at the top right of the page
> 
> ![image](https://private-user-images.githubusercontent.com/10872799/316640951-8d547bf0-f8ed-476a-89b4-d4a7c99c1357.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDI0MTUsIm5iZiI6MTcxMTUwMjExNSwicGF0aCI6Ii8xMDg3Mjc5OS8zMTY2NDA5NTEtOGQ1NDdiZjAtZjhlZC00NzZhLTg5YjQtZDRhN2M5OWMxMzU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAxMTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxMGQ2ODMyMjlmY2UzNDdjYjgwZTQ4ZTA5ZDA0OWVhNTA3YTM1NjljMDZlYzJlYjAzNmQ1NGNlNmY0MzM0NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lb1OKZbZJZ95UiP5qg1CxNmQkI5Bo1e12rfD7hPIc14)
> 
> ![image](https://private-user-images.githubusercontent.com/10872799/316641147-5657cf51-6e41-46e3-a74c-93901bd32031.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDI0MTUsIm5iZiI6MTcxMTUwMjExNSwicGF0aCI6Ii8xMDg3Mjc5OS8zMTY2NDExNDctNTY1N2NmNTEtNmU0MS00NmUzLWE3NGMtOTM5MDFiZDMyMDMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDAxMTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwOTEyMzAzZGJiYTQ1ODA5OTU1Y2M3MTE4NmExOGVjNGI5ZjJkYzAyMmZiMTEwZGIzNzE0MDEzOWE3NGI3ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6SrDxZ37Vi6VcGj-axPsd_jNIW0KmkTo4VD4LhULWi4)

Also, if you have AdBlockPlus or uBlock Origins, the Accept cookies popup might not show. if this is the case you will need to disable the adblocker, accept the cookies, then you can re-enable your adblocker

**Comment by homes32** [comment]
>I have attached logs of the latest build where the following applications have links, but do not work in PE, yet they all exist with EXE files as well as their supporting files in the output programs folder of the build.

Are you by chance booting via PXE or via the Host Boot option?

If so that would explain the issue. With either of these 2 options you need everything packed in the .wim file (aka Run From RAM).

You can enable the Run all programs from RAM (Boot.wim) option on the Source Config script to accomplish this.
![image](https://github.com/PhoenixPE/PhoenixPE/assets/6519152/dcc2332f-b233-4bb6-b6c6-a2e9465aabd1)

**Comment by TheNicestGuy24** [comment]
> > I have attached logs of the latest build where the following applications have links, but do not work in PE, yet they all exist with EXE files as well as their supporting files in the output programs folder of the build.
> 
> Are you by chance booting via PXE or the Host Boot option?

I do not use PXE to boot the ISO.  After the build creates the ISO, I then put that ISO onto my Ventoy USB drive (https://www.ventoy.net/en/index.html) and then choose the Phoenix ISO to boot from the ventoy boot menu.

When booting an ISO via ventoy, you have 2 options.  Normal boot or WIM boot.  I have tried both options and still have the same issue, if not built to run with RAM, then program isn't there / won't launch.

Do you think perhaps the way that Ventoy is booting the ISO is causing this?

**Comment by homes32** [comment]
> Do you think perhaps the way that Ventoy is booting the ISO is causing this?

Yeah, in a way. In normal mode Ventoy emulates a cdrom drive to mount the ISO and boot. For some reason PhoenixPE isn't picking up this virtual image so it never gets mounted in WinPE. I am able to reproduce the behavior now so will see what I can figure out.

Using wimboot mode is essentially the same as PXE booting. Everything needs to be in boot.wim as that's all Ventoy will extract from the ISO and boot.

**Comment by april83c** [comment]
I'm having the same issue (the programs are in the Programs folder, but when actually booted into the PE, the shortcuts to them have no icon and don't open), but I'm not using Ventoy — I just wrote the ISO to a flash drive directly with Rufus

**Comment by homes32** [comment]
I spent some time analyzing Ventoy's source code trying to get to the bottom of the issue with Ventoy not mounting the source ISO after boot. It's surprisingly clunky.

Basically Ventoy works by attaching the chosen ISO file at the BIOS/UEFI level in order to extract and load boot.wim into memory. The booted OS has no knowledge of this mounted ISO as it only lives at the BIOS/UEFI firmware level. In order to get the ISO to show after boot is to re-mount the image. Ventoy provides a couple methods of support for this.

1. The location and path to the ISO image is stored in low memory where it can be read by us in WinPE and we can use the information to mount the ISO manually.
2. Ventoy will try and hook into the boot process and mount the source ISO automatically. This is hit or miss as there is alot of variation in different OS.

The Option 2 hook process looks like this:

1. The Ventoy bootloader mounts the ISO at the firmware level
2. _boot.wim_ is loaded into memory
3. Ventoy looks up the value of _HKLM\SYSTEM\Setup\CmdLine_
4. Ventoy patches _boot.wim_ in memory to replace the setup program referenced in _HKLM\SYSTEM\Setup\CmdLine_ with vtoyjump.exe
5. Ventoy creates the _x:\windows\system32\ventoy_ directory
6. Ventoy copies the original .exe referenced in _HKLM\SYSTEM\Setup\CmdLine_ to the _x:\windows\system32\ventoy\_ dir
7. Ventoy copies _vtoyjump.exe_ to _x:\windows\system32\ventoy\WinLogon.exe_  
8. Ventoy runs _WinLogon.exe <CmdLine>_ where CmdLine is the value of _HKLM\SYSTEM\Setup\CmdLine_
9. The fake WinLogon.exe (vtoyjump.exe) scans low memory for the ventoy signature and reads ISO path
10. WinLogon.exe (vtoyjump.exe) then scan attached disks for ISO path read from memory
11. WinLogon.exe (vtoyjump.exe) mounts the source ISO if found
12. WinLogon.exe (vtoyjump.exe) renames the "fake" setup exe back to _vtoyjump.exe_
13. WinLogon.exe (vtoyjump.exe) copies back the original .exe from _x:\windows\system32\ventoy\_ to _x:\windows\system32\_
14. WinLogon.exe (vtoyjump.exe) launches the original command referenced in _HKLM\SYSTEM\Setup\CmdLine_ and remains resident in memory.

Based on debug logs (at the ventoy main menu press 'c' and enter 'vtdebug on' at the grub prompt) we can determine that ventoy is not correctly handling our setup loader (AutoIt3.exe) and fails to remap the metadata to point to vtoyjump.exe

The code contains specific workarounds for winpeshl and PECMD so that explains why there are no problems with projects like Win10XPE that use PECMD as their setup loader. It does contain *some* support for what it calls *custom* loaders, but this support is obviously flawed.

So auto mount by ventoy is out of the question until if/when ventoy fixes this. The good news? Option 1 is a viable solution so I have modified the PhoenixPE startup process to search low memory for the ventoy signature on startup and if found mount the source ISO file for us.

**Comment by TheNicestGuy24** [comment]
Thank you for looking into this thoroughly and providing a fix, it is greatly appreciated!

I took the [000-PreShell.script] file and replaced that in my shell directory of my phoenix PE folder however, when I build and then boot with ventoy I still have the same issue if the program wasn't set to run in ram, then it won't launch / ins't there.

Is there something else I am supposed to be adding in order to make this work in Ventoy?  I tried both normal boot and wim boot in ventoy with the same results.

**Comment by homes32** [comment]
> Is there something else I am supposed to be adding in order to make this work in Ventoy? I tried both normal boot and wim boot in ventoy with the same results.

Did you click the refresh button in PEBakery after you replaced the 000-PreShell.script? PEBakery caches scripts for speed, so if you didn't then your actually still running the old version of the script.

If you still are having issues after you have confirmed the build log shows `PreShell v1.1.0.0` like  the example below please post the contents of  `X:\Windows\System32\PhoenixPE.log` after you boot into PhoenixPE.

```
- PEBakery Build <PreShell - Run> -
Built    by PEBakery 1.1.1
Exported by PEBakery 1.1.1

Started  | 2024-06-04 06:27:22 PM -05:00
Finished | 2024-06-04 06:27:24 PM -05:00
Took 0:00:02


<Host Environment>
Windows      | 10.0.19045.0 (x64)
.NET Runtime | 6.0.30 (x64)


<Log Statistics>
Success      : 153
Warning      : 0
Overwrite    : 22
Error        : 0
Info         : 44
Ignore       : 39
Muted        : 0


<Scripts>
[  1/  2] PhoenixPE v1.0.5.0 | 0.1s | PhoenixPE\script.project
[  2/  2] PreShell v1.1.0.0  | 2.5s | PhoenixPE\Shell\000-PreShell.script
```

**Comment by homes32** [comment]
Which applications did you enable?

I'm not able to reproduce this in a stock build. I did reproduce what you describe once, after enabling certain applications.

If you are able, please confirm if you can boot successfully with a stock build and if so enable your chosen apps one by one and confirm which causes the ventoy detection to stop working.

Thank you!

**Comment by TheNicestGuy24** [comment]
I started with a clean brand new copy of the builder, updated the pre-shell file in the shell folder to the newest version which has the ventoy fix in it.  I then attempted a build without adding or removing anything, Firefox failed in the build as I didn't update the plugin to the new version, so I unchecked firefox from the build, then built again.  The only application that is built into the stock build (aside from Firefox and system type apps) is Notepad++, which ran fine in the PE because it is set to run from RAM.  I then unchecked notepad++ to run from RAM and rebuilt.  Notepad++ does run when not set to run from ram but does give a couple of errors:  Load langs.xml failed and Load Y:\Programs\Notepad++\stylers.xml failed but then it does open the application after that.  PENetwork does work but doesn't have the option to run from ram or not, so I assume it is hard coded to run from RAM.

Now going back to the build I was previously using when asking if I needed to do something additional to make this work in Ventoy.  I enabled a LOT of applications in that build, most everything that is available in the build is in that build.  All the things set to run from RAM, does work.  The very large majority doesn't work and is set to NOT run from ram.  The only application that is set to NOT run from RAM that does work is Aomei backupper.  The on-screen keyboard doesn't have a run from ram setting and it doesn't work either.  Command prompt does work, again, no setting to run from ram.

I don't see an application that I can use in the PE to take screenshots but I can screenshot the build showing some of the apps I have in the build.

![image](https://github.com/PhoenixPE/PhoenixPE/assets/164514930/31dce5a2-7176-4703-8580-233aea36ba95)

In the image above, none of the applications checked in the build work, they just have a link in the start menu that gives you a "problem with shortcut" pop up when launching them except for Aomei Backupper, HxD, and 64dbg.  Aomei backup is set to NOT run from ram, but HxD and 64dbg are set to run from RAM and they also work.  But literally all other applications that are set to NOT run from ram have broken shortcuts because the application doesn't exist.

Please let me know what else I can provide to make this work.  I was running ventoy .98 (which had this same issue) and today I updated to .99 and still have the same issue.

I really do appreciate your time and expertise to look into this, it is greatly appreciated!

**Comment by homes32** [comment]
looking at your log, it appears that the program can't find the USB device.

```
X:\ is in PhysicalDrive-1 
Could not open the disk<\\.\PhysicalDrive-1>, error:2
```
error 2 = ERROR_FILE_NOT_FOUND

likewise
```
Current Host Volume Information:
08:03:28:463   ...... Host:  HKEY_LOCAL_MACHINE\SYSTEM\MountedDevices
"X:"  "0xFC57B2D94E68CB4DAB7903CFA2F6B750"
```
indicates that the only drive attached to the system is the `X:` drive which should be the FBWF/UWF overlay for the .wim file. no sign of whatever physical disk/device your booting from.

do you have another USB drive you could try and see if it shows up?

**Comment by graphixillusion** [comment]
I'm still having problems using ventoy: Y: is not mounted and the internal hdd of the computer are in offline mode. I can put them online using diskpart, doesn't work using the mmc. Any clue?

**Comment by homes32** [comment]
I'm curious what drive make/model you have. Have you been able to try a different make/model USB drive to see if we can narrow down the issue? You can also try running `chkdsk /r` in case there are any errors that is causing windows to not want to mount the drive.

If windows isn't putting it online there is really nothing I can do. We need to be able to see the drive with the WinAPI `GetLogicalDriveStrings()` and ` GetLogicalDrives()` functions in order to find and mount the ISO image.

**Comment by homes32** [comment]
Perhaps it's related to this issue https://github.com/ventoy/Ventoy/issues/1975 and caused by a firmware bug in the ASM235CM USB controllers used by some manufactures.

**Comment by graphixillusion** [comment]
I've tried with two different usb. The USB pendrive is a Jetflash Transcend 16GB (no ventoy, just the WINPE flashed with rufus).
The ventoy's one is an sd card with a generic USB adapter. I usually don't have any problems with other PEs using these hw.

**Comment by homes32** [comment]
great to hear! 
the `Could not open the disk<\\.\PhysicalDrive-1>, error:2` errors you were getting make alot more sense now.

Well, it wasn't a wasted exercise anyway as the issue with ventoy being able to find and mount the ISO still needed to be addressed.

**Comment by TheNicestGuy24** [comment]
I can confirm that what graphixillusion said is correct.  If you include the forensic tool "WinFE Write Protect Tool" in the PE, it breaks all the programs that aren't set to run from RAM.  If you remove that tool and then build and run the PE, all programs work fine now.

Thanks for all your help with this!!

**Comment by graphixillusion** [comment]
If you want to keep it you can, you must remove the launch on boot option and it will be ok.

**Comment by TheNicestGuy24** [comment]
Ok, thanks!  On a side note, does anyone know how to make this either separate or not be stacked up on top of each other?

![image](https://github.com/PhoenixPE/PhoenixPE/assets/164514930/51496f98-03be-4e4c-87e9-b119f147bcbe)

**Comment by homes32** [comment]
Disable either the BGInfo or DesktopInfo script. Its silly to have both enabled as they do the essentally same thing. The benifit of DesktopInfo is its actively developed and the info is displayed in realtime. BgInfo is a static snapshot made at startup. Some people prefer it due to personal preference in configuration and the fact that it does not remain resident in memory.

If you really want both for some reason you can modify the config file to change the display position, then specify the file as the custom config.

**Comment by TheNicestGuy24** [comment]
> Disable either the BGInfo or DesktopInfo script. Its silly to have both enabled as they do the essentally same thing. The benifit of DesktopInfo is its actively developed and the info is displayed in realtime. BgInfo is a static snapshot made at startup. Some people prefer it due to ease of configuration with a GUI vs DesktopInfo's text based config and the fact that BGInfo does not remain resident in memory.
> 
> If you really want both for some reason you can modify either config file to change the display position, then specify the file as the custom config.

Perfect, thank you!  I did a custom config for BGInfo and moved it over and now both are displaying properly.  Thanks again!  Great work on the PE.

**Comment by 3gmgithub** [comment]
FYI I confirmed when using Ventoy the programs only work when loaded into RAM...
